---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  selector:
      matchLabels:
        app: influxdb
  replicas: 1
  #restartPolicy: Always
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb-img
        imagePullPolicy: Never
        volumeMounts:
        - name: dockerd
          mountPath: /var/run/docker.sock
        ports:
        - containerPort: 8086
          name: influxdb
      volumes:
      - name : dockerd
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
      matchLabels:
        app: mysql
  replicas: 1
  #restartPolicy: Always
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-img
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
      matchLabels:
        app: wordpress
  replicas: 1
  #restartPolicy: Always
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wp-img
        imagePullPolicy: Never
        env: 
        - name: DB_HOST
          value: mysql
        ports:
        - containerPort: 5050
          name: wordpress
      initContainers:
      - name: init-db
        image: init-db-img
        imagePullPolicy: Never
        env: 
        - name: DB_HOST
          value: mysql    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
      matchLabels:
        app: phpmyadmin
  replicas: 1
  #restartPolicy: Always
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: pma-img
        imagePullPolicy: Never
        env: 
        - name: DB_HOST
          value: mysql
        ports:
        - containerPort: 5000
          name: phpmyadmin
      initContainers:
      - name: init-db
        image: init-db-img
        imagePullPolicy: Never
        env: 
        - name: DB_HOST
          value: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
      matchLabels:
        app: grafana
  replicas: 1
  #restartPolicy: Always
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana-img
        imagePullPolicy: Never
        env: 
        - name: DB_HOST
          value: influxdb
        ports:
        - containerPort: 3000
          name: grafana
      initContainers:
      - name: init-influx
        image: init-influx-img
        imagePullPolicy: Never
        env: 
        - name: DB_HOST
          value: influxdb
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nginx
#  labels:
#    app: nginx
#spec:
#  selector:
#      matchLabels:
#        app: nginx
#  replicas: 1
  #restartPolicy: Always
#  template:
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      containers:
#      - name: nginx
#        image: nginx-img
#        imagePullPolicy: Never
#        ports:
#        - containerPort: 80
#          name: nginx
#---