apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
      matchLabels:
        app: wordpress
  replicas: 1
  #restartPolicy: Always
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wp-img
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wordpress