apiVersion: v1
kind: Service
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
    ports:
    - port : 5050
      targetPort: 5050
    selector:
        app : wordpress
    type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin
    labels:
        app: phpmyadmin
spec:
    ports:
    - port : 5000
      targetPort: 5000
    selector:
        app : phpmyadmin
    type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    ports:
    - port : 3306
    selector:
        app : mysql
---
apiVersion: v1
kind: Service
metadata:
    name: grafana
    labels:
        app: grafana
spec:
    ports:
    - port : 3000
      targetPort: 3000
    selector:
        app : grafana
    type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
    name: influxdb
    labels:
        app: influxdb
spec:
    ports:
    - port : 8086
    selector:
        app : influxdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.101-192.168.99.105

---
#apiVersion: v1
#kind: Service
#metadata:
#    name: nginx
#    labels:
#        app: nginx
#spec:
#    ports:
#    - port : 80
#      targetPort: 80
#    - port : 443
#      targetPort: 443
#    selector:
#        app : nginx
#    type: LoadBalancer
#---