apiVersion: v1
kind: Service
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
    ports:
    - port : 5050
      targetPort: 5050
      nodePort: 5050
    selector:
        app : wordpress
    type: LoadBalancer